# -*- coding: utf-8 -*-
"""SI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qkk6Ij1mkrTNcyOOgDMidEaI_M_egKSl
"""

# simple_interest_app.py
import streamlit as st

st.title("💰 Simple Interest Calculator")

# Input fields
principal = st.number_input("Enter Principal Amount (₹):", min_value=0.0, value=1000.0)
rate = st.number_input("Enter Rate of Interest (% per year):", min_value=0.0, value=5.0)
time = st.number_input("Enter Time (in years):", min_value=0.0, value=1.0)

# Calculate button
if st.button("Calculate Simple Interest"):
    simple_interest = (principal * rate * time) / 100
    total_amount = principal + simple_interest

    st.success(f"Simple Interest: ₹{simple_interest:.2f}")
    st.info(f"Total Amount after {time} years: ₹{total_amount:.2f}")