# -*- coding: utf-8 -*-
"""STREAMLIT LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eoN80OO2qR9Eyhovyf9Kc39c7xjxeHiS
"""

# simple_test.py
import streamlit as st

st.title("Simple Test App")
st.write("If you see this, Streamlit is working!")

try:
    import yfinance as yf
    st.write("✅ yfinance imported successfully")
except Exception as e:
    st.write(f"❌ yfinance import failed: {e}")

try:
    import pandas as pd
    st.write("✅ pandas imported successfully")
except Exception as e:
    st.write(f"❌ pandas import failed: {e}")